### PR TITLE
Added Network Class

### PR DESCRIPTION
**Pull request by vatsalparekh**
Takes care of #8 and #1

### CODE REVIEW

**Comment by dharmit** [comment]
I don't see anything getting printed when I do `python3 tinyutils.py`. Can you elaborate what has been done here?

**Comment by vatsalparekh** [comment]
I added this network file here, which uses other files to parse data. 
I felt like network file should return the data when its called, so in our context the main tinyutils will call

**Comment by vatsalparekh** [comment]
I added this network file here, which uses other files to parse data. 
I felt like network file should return the data when its called, 
so in our context the main tinyutils will take the specific `-n` switch and than network file will return data to it.

**Comment by dharmit** [comment]
> I added this network file here, which uses other files to parse data.

`network.py` file doesn't have any documentation whatsoever. So, it doesn't ring bells as to what it is doing. Same for `command.py` and `parse.py`. 

I am sure your intentions have been good. But without proper documentation, it's difficult to understand what you're trying to do.

I recommend adding comments using Python's [docstring specification](https://www.python.org/dev/peps/pep-0257/#specification).

> so in our context the main tinyutils will take the specific -n switch and than network file will return data to it.

And does it do so yet? I mean by this commit. Not any future commits/PR.

**Pull request closed without merging**
